# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below
  # License Options:
  # - None
  # - AGPL-3.0 
  # - Apache-2.0 
  # - BSD-2-Clause 
  # - BSD-3-Clause 
  # - EPL-1.0 
  # - GPL-2.0 
  # - GPL-3.0 
  # - LGPL-2.1 
  # - LGPL-3.0 
  # - MIT 
  # - MPL-2.0 
  # - Unlicense 

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: webprogress                       # A unique namespace for your toolbox
  toolbox_name: HTTP Progress Bar                   # Name of the MATLAB toolbox
  author_name: Eivind Hennestad
  author_email: ehennestad@gmail.com
  author_company: ''                                # Author's company or organization
  toolbox_summary: Download and upload files over HTTP with a live progress display
  toolbox_description: |
    Download files from the web and upload files to the web while showing live progress, using MATLAB's HTTP interface.
    Progress is shown in a waitbar, in a progress dialog attached to an app figure, or in the Command Window. It includes the transferred size, the percentage and an estimate of the remaining time.
  dependencies:                                     # Required MATLAB products
    - MATLAB

# Publishing options
codecov:
  badge_token: null

fileexchange:
  fex_url: null
